### PR TITLE
SQL datastore

### PR DESCRIPTION
**Pull request by RomeshA**
Creating this PR for initial review

The idea is following on from our discussions on Slack, for it to be possible for `DataStore` to be backed by different storage mechanisms. This is implemented in this PR by implementing derived classes that implement only the subset of datastore operations that interact with the underlying storage. The result is that most of the heavy lifting of `DataStore` is unchanged and common to all of the storage backends. Three backends are implemented here

- `RedisDataStore` the same as before
- `SQLDataStore` which implements storage via SQLalchemy, could in turn be backed by any SQL backend supported by SQLalchemy e.g. mssql, postgres, sqlite
- `DiskDataStore` which uses the file system as the database :) 

These all derive from `DataStore` so the only real change required in the application code is replacing 

```
datastore = ds.DataStore(redis_url=<>)
```

with

```
datastore = ds.DataStore.create(uri=redis_url)
```

and `DataStore.create` is a static method that instantiates the appropriate kind of DataStore depending on the URI. So for example, in `config_cascade.py` the database URI could be any of

```
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/8')
REDIS_URL = os.getenv('REDIS_URL', 'sqlite:///cascade.db')
REDIS_URL = os.getenv('REDIS_URL', 'disk:/mnt/e/projects/atomica_apps/bin/cascade')
```

and indeed changing the `REDIS_URL` to each one of these should result in the appropriate backend being used e.g. the sqlite one will create a file called `cascade.db`, the path in the final one will create files inside the specified folder

(of course, the application code should later be changed so that the env variable is `DATASTORE_URI` or something like that, because the `REDIS_URL` is still needed for celery)

### CODE REVIEW

**Comment by RomeshA** [comment]
(also, I think it would make sense to have an empty `DATASTORE_URI` correspond to `sqlite:///:memory:` because then it would be trivial to test the setup on a system that doesn't have redis or any other database set up)

**Comment by cliffckerr** [comment]
@RomeshA Looks wonderful, thank you so much! Just a few minor stylistic things:
* I know the Python design philosophy is "There should be one, and just one, obvious way of doing things." Unfortunately, sometimes there isn't just one obvious way :) In which case my fallback is "If a given command could only be sensibly interpreted one way, it should work that way". So, if I try to do `datastore = ds.DataStore(redis_url=<>)`, I think this should be an alias to `datastore = ds.DataStore.create(uri=redis_url)`, since I couldn't mean anything else, and likewise for the other database options. 
* Aside from kwargs, I would allow DataStore to be called directly rather than just with the `create()` property (which makes sense, but is also a nonstandard way of making class instances, so might be hard for people to intuit). The way it currently is, I'm not quite sure what would happen if you _did_ do `ds.DataStore(redis_url=<>)`...
* Only other minor thing, maybe we could we call it FileDataStore rather than DiskDataStore?

**Comment by RomeshA** [comment]
@cliffckerr Great!  I'm not too fussed really, since it's more stylistic and esp. since this is Sciris rather than Atomica, but my thinking was that `DataStore` is actually an abstract base class because it doesn't implement the methods like `_set` etc. so normally you'd actually be _unable_ to instantiate it directly in languages that formally implement it (in C++ you'd define `_set` etc. to be a pure virtual function to formalize it).  I'd say that just doing `ds.RedisDataStore(uri=<>)` is cleaner and preferable to making the `DataStore` constructor more complex - if you're going to change `uri=` to `redis_url=` you may as well just write `RedisDataStore` instead. Having `ds.DataStore(redis_url=<>)` produce a `RedisDataStore` could also be confusing just because it would be unexpected that the `DataStore` constructor returns a different type of object (also depending on the arguments!) - that would be even more nonstandard than having a static method as an alternative constructor (actually I think using static methods and class methods as alternate constructors is reasonably standard?)

Part of the difficulty though, is that `DataStore` is a class, not a function, so its constructor has a special meaning. An alternative halfway house could be if you wanted to rename `DataStore` to something different e.g. `BaseDataStore` and then actually write a function

```
def DataStore():
    ....
```

with the content of what's currently in `DataStore.create()` - then the interface would be `ds.DataStore(uri=<>)` and it would be fine that it could return any one of several different types, and it would be reasonably pythonic to support arguments like `redis_url` as well. That might be the cleanest solution overall to provide your desired interface actually... 👍  

I do subscribe to a slightly different version of "If a given command could only be sensibly interpreted one way, it should work that way" though - I feel more like "If a given command could only be sensibly interpreted one way, it should not work in a different way" - I don't think the fact that it has only one sensible interpretation implies that it needs to work at all!

**Comment by RomeshA** [comment]
Actually another option under the "one, and just one, obvious way of doing things" could be to define a function 'make_datastore()` or something like that, and have that be the standard interface for getting datastores out of scirisweb, rather than having it be a static method of `DataStore`

**Comment by cliffckerr** [comment]
@RomeshA Yeah actually that's exactly what I was thinking, rename the current `DataStore` to `BaseDataStore`. But if `DataStore` is a function then by convention it should probably be `datastore()`, which is OK too. I guess the question is, do we really need separate classes? The other option would be to have something like:
```
def __init__(self):
  if self.is_redis:
    self.make_redis()

def make_redis(self):
  def get(self, key):
    return self.redis.get(key)
  self.get = get
```

Kind of ugly I guess, but at least the ugliness is hidden...

**Comment by RomeshA** [comment]
You _could_ have a single class... but my feeling is that the multiple classes make it easier to work with as a developer (e.g. the implementation of `DiskDataStore` is very simple and clear, yet provides full datastore functionality and is completely independent of `RedisDataStore`, all of which is I think is valuable as a developer) - mixing the backends all up in a single class would make it harder to follow the logic of what's happening (it's quite nice actually, how you can read the methods for `DataStore` and see how it manages naming keys etc. independently of how they're being stored).

So I'll go ahead and implement `BaseDataStore` and `datastore()` then? Preference for the datastore uri environment variable to replace `REDIS_URL`?  `DATASTORE_URI`?

**Comment by cliffckerr** [comment]
@RomeshA As you mentioned we still have to have `REDIS_URL` for Celery, so I would prefer to leave it, and have `DATASTORE_URI` as an alternate, with `DATASTORE_URI` taking precedence.

I'm also a little concerned about breaking backwards compatibility by removing `sw.DataStore`, but I guess it's not too much trouble to update our apps, and better to do it now rather than get stuck on weird legacy things in future :) (We could also just make `sw.DataStore()` an alias for `sw.datastore()`, but that seems confusing.)

**Comment by cliffckerr** [comment]
Hmm just thinking out loud, somehow because a datastore is a big heavy "thing", it still feels more natural to me to have `sw.DataStore()` rather than `sw.datastore()` (I agree the latter would make more sense as `sw.make_datastore()`...this just seems like a lot of extra letters to type if it's the only way to create one...but on the other hand, it's not a command you're going to be typing a lot). Thoughts? Do you have a strong preference for having `sw.make_datastore()` as the one canonical way to create a datastore? I could be persuaded :)

It is a nice parallel to have
```
datastore = sw.DataStore()
app = sw.ScirisApp()
```
but equally, confusing since `ScirisApp` is a class and `DataStore` is a function, so `isinstance(my_datastore, sw.DataStore)` would lead to unexpected results...

**Comment by RomeshA** [comment]
I think the 5 extra characters in `make_datastore()` would be worth the clarity they provide :)

**Comment by RomeshA** [comment]
I made all those changes so I'm pretty satisfied that this should be good to go. In view of scirisweb's role as a foundation for other tools, I think it'll be clearer to use `DATASTORE_URL` for the datastore in the same way that `BROKER_URL` is used for celery, and if desired, a sciris app's config file could do

```
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/8')
DATASTORE_URL = REDIS_URL
BROKER_URL = REDIS_URL
```

if they wanted to use redis for all of them (so a straightforward generalization of what's already done for celery) - I think this will be much clearer about which URL is being used for which backend component (i.e. for scirisweb itself not to contain it's own fallback logic) and it makes sense for scirisweb not to privilege Redis noting that it's also possible someone might want to use SQL+RabbitMQ and thus not use Redis for anything at all

**Review by cliffckerr — APPROVED** [review]

**Pull request merged**
